global using Carter;
global using Mapster;
global using Marten;
global using Catalog.Api.Models;
global using Catalog.Api.Exceptions;
global using FluentValidation;
global using BuildingBlock.Behaviors;
global using BuildingBlock.Exceptions.Handler;
global using Catalog.Api.Data;
global using Marten.Pagination;
global using Catalog.Api.Dtos;
global using BuildingBlock.CQRS;
using Catalog.Api.Validators;