services:
  catalogdb:
    image: postgres:17.6

  basketdb:
    image: postgres:17.6

  distributedcache:
    image: redis

  orderdb:
    image: postgres:17.6

  messagebroker:
    image: rabbitmq:management

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: ..
      dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: ..
      dockerfile: src/Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: ..
      dockerfile: src/Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: ..
      dockerfile: src/Services/Ordering/Ordering.Api/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: ..
      dockerfile: src/ApiGateways/YarpApiGateway/Dockerfile

  eshop.ui:
    image: ${DOCKER_REGISTRY-}eshopui
    build:
      context: ../client/eshop-app
      dockerfile: Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_order: