global using Basket.Api.Models;
global using Carter;
global using Mapster;
global using Mediator;
global using FluentValidation;
global using Basket.Api.Exceptions;
global using Marten;
global using Basket.Api.Data;
global using Basket.Api.Dtos;